@startuml
'https://plantuml.com/component-diagram
left to right direction

package Interfaces {
    [REST API] as rest
    [Consumer] as con
    [Job] as job
}

package Application {
    [App service API] as asa
    [App service impl] as asi
    [OuterServiceProxy API] as ospa
}

package Domain {
    [Domain service API] as dsa
    [Domain service impl] as dsi
    [Domain aggregate] as da
    [Repository API] as rea
}

package Infrastructure {
    [Repository impl] as rei
    [OuterServiceProxy Impl] as ospi
    [System config]
}


database "MySql" as mysql{
}

database "Redis" as redis{

}


rest --> asa
con --> asa
job --> asa
asi --> da
asi --> dsa
asi --> rea
asi --> ospa

asi ..|> asa
dsi ..|> dsa
rei ..|> rea
ospi ..|> ospa
rei --> mysql
rei --> redis

rei --> da

dsi --> rea

@enduml