@startuml
left to right direction

actor "MessageConsumer" as mc
actor "Scheduler" as sch
actor "Customer" as cus
actor "Staff" as sta

(query sku) as query
    note right of query
    Query sku information by code.
    end note
(maintain sku) as maintain
    note right of maintain
    Create or modify sku. A sku include
    information such as Code, Name,
    Maximum in warehouse,
    Minimum in warehouse,
    Maximum on shelf,
    Minimum on shelf and so on.
    After an sku is created,
    a message is sent.
    end note
'(take stock) as tast
'    note right of tast
'    Query sku details from
'    shelf or warehouse
'    to check the stock
'    end note
(replenish warehouse) as sw
    note right of sw
    Get the goods ordered from supplier
    into warehouse.
    end note
(replenish shelves) as sts
    note right of sts
    Move the goods from warehouse to shelves
    end note

sta --> query
sta --> maintain
'sta --> tast
sta --> sw
sta --> sts

(purchase goods) as buy
    note right of buy
    If shelf goods enough for customer,
    deduct inventory from shelf.
    if shelf goods not enough but
    warehouse goods enough for customer,
    deduct inventory from shelf first,
    then deduct the remains from warehouse.
    if warehouse goods still not enough
    then purchase failed.
    end note
'(refund goods) as refund
'    note right of refund
'    Refunded goods directly add back
'    to warehouse.
'    end note

cus --> buy
'cus --> refund

(auto Inventory inspection) as auin
    note right of auin
    An automatic job runs on a specific
    schedule to send the replenishment message
     when the inventory level falls
     below the threshold.
    end note

sch --> auin

(warehouse replenishment) as stre
    note right of stre
    Automatically contact the supplier to
    order the specific goods when
    receiving the stock replenishment message.
    end note
(shelf replenishment) as shre
    note right of shre
    Call a staff to move goods from warehouse
     to shelf when receiving the shelf
     replenishment message.
    end note
(inventory initialization) as ii
    note right of ii
    Initialize shelf and warehouse inventories
    after receiving the message.
    end note

mc --> stre
mc --> shre
mc --> ii
@enduml