@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Staff" as staff
actor "Customer" as cus
actor "Scheduler" as sch
participant "MessageConsumer" as mc
participant Service as ser
participant Repository as rep
database Database as db
queue MessageBroker as mb
participant OuterServiceProxy as proxy

== Sku management ==
opt modify sku
    staff -> ser: query sku
    activate ser
    ser --> staff: stu info
    deactivate
end

staff -> ser: save sku
activate ser
    ser -> rep: save sku
    activate rep
        rep -> db: db op
        activate db
        db --> rep: return
        deactivate db
    rep --> ser: return
    deactivate rep
    opt if creation
        ser -> mb: send created message
        activate mb
        mb --> ser: ack
        deactivate mb
    end
ser -> staff: return
deactivate ser

== Initialization ==

mb -> mc: push sku created message
activate mc
    mc -> ser: initialize inventory
    activate ser
    ser -> rep: create shelf and warehouse inventories
    activate rep
        rep -> db: db op
        activate db
        db --> rep: return
        deactivate db
    rep --> ser: return
    deactivate rep
    ser --> mc: return
    deactivate ser
mc --> mb: ack
deactivate mc

== Purchase ==

cus -> ser: purchase goods
activate ser
ser -> ser: check if inventory enough
    activate ser
    deactivate ser
alt shelf enough
    ser -> rep: deduct from shelf
    activate rep
        rep -> db: db op
        activate db
        db --> rep: return
        deactivate db
    rep --> ser: return
    deactivate rep
    ser --> cus: return
else warehouse enough
    ser -> rep: deduct from shelf and warehouse
    activate rep
        rep -> db: db op
        activate db
        db --> rep: return
        deactivate db
    rep --> ser: return
    deactivate rep
    ser --> cus: return
else no enough inventory
    ser --> cus: purchase failure
end
deactivate ser


@enduml

@startuml

actor "Staff" as staff
actor "Customer" as cus
actor "Scheduler" as sch
participant "MessageConsumer" as mc
participant Service as ser
participant Repository as rep
database Database as db
queue MessageBroker as mb
participant OuterServiceProxy as proxy

== Inventory inspection ==

sch -> ser: run inventory inspection
activate ser
    ser -> rep: query inventory and sku info
    activate rep
        rep -> db: db op
        activate db
        db --> rep: return
        deactivate db
    rep --> ser: return
    deactivate rep
    loop all inventory
        opt lower than threshold
            ser -> mb: send replenishment message\n(shelf or warehouse)
            activate mb
            mb --> ser: ack
            deactivate mb
        end
    end
    deactivate ser

mb -> mc: push replenishment message
activate mc
    alt shelf replenishment
        mc -> ser: shelf replenishment
        activate ser
            ser -> proxy: send shelf replenishment \n SMS message to staff
            activate proxy
            proxy --> ser: success
            deactivate proxy
        ser --> mc: success
        deactivate ser
    else warehouse replenishment
        mc -> ser: warehouse replenishment
        activate ser
            ser -> proxy: order goods from supplier system interface
            activate proxy
            proxy --> ser: success
            deactivate proxy
        ser --> mc: success
        deactivate ser
    end
mc --> mb: ack
deactivate mc

== Replenishment ==

staff -> ser: replenish warehouse
note right
after receiving the goods ordered from supplier
end note
activate ser
    ser -> rep: add warehouse inventory
    activate rep
        rep -> db: db op
        activate db
        db --> rep: return
        deactivate db
    rep --> ser: return
    deactivate rep
ser --> staff: return
deactivate ser

staff -> ser: replenish shelves
activate ser
    ser -> rep: deduct warehouse inventory \n and add shelf inventory
    activate rep
        rep -> db: db op
        activate db
        db --> rep: return
        deactivate db
    rep --> ser: return
    deactivate rep
ser --> staff: return
deactivate ser
@enduml